CREATE TABLE [dbo].[CAT_PERFILES] (
    [PER_PK_CVE]        INT          IDENTITY (1, 1) NOT NULL,
    [PER_DS_NOMBRE]     VARCHAR (50) NULL,
    [EST_PK_CVE]        INT          NULL,
    [PER_US_MODIFICADO] VARCHAR (20) NULL,
    [PER_FE_ULT_MOD]    DATETIME     NULL,
    [PER_FE_CREADO]     DATETIME     NULL,
    PRIMARY KEY CLUSTERED ([PER_PK_CVE] ASC)
);

