CREATE TABLE [dbo].[SYS_PERFILES_ACCIONES] (
    [SPA_PK_ID] INT IDENTITY (1, 1) NOT NULL,
    [SMN_PK_ID] INT NULL,
    [SEO_PK_ID] INT NULL,
    [CPL_PK_ID] INT NULL,
    [SMU_PK_ID] INT NULL,
    [SAN_PK_ID] INT NULL
);

