CREATE TABLE [dbo].[SYS_SUCURSALES_USUARIOS] (
    [SSU_PK_ID] INT IDENTITY (1, 1) NOT NULL,
    [SMN_PK_ID] INT NULL,
    [SEO_PK_ID] INT NULL,
    [CPA_PK_ID] INT NULL,
    [SUO_PK_ID] INT NULL
);

